// Package webfs embeds the built React UI for release builds. During
// development the Vite dev server serves the UI and proxies /api to the daemon;
// for release, this package's embedded files are served by the daemon.
//
// dist/ is generated by `make build-ui` (or the Docker web-build stage) and is
// not committed. A tracked dist/.gitkeep keeps //go:embed valid for bare
// `go test` / `go build` without Node; that placeholder is not a product UI.
package webfs

import "embed"

// Dist holds the built static assets under dist/.
//
//go:embed all:dist
var Dist embed.FS
